name: todoapp
description: "My first Flutter app"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.8
  google_fonts: 
  path_provider:
  firebase_core: 
  firebase_auth: 
  cloud_firestore: ^5.4.4 
  shared_preferences: ^2.3.2
  roundcheckbox: ^2.0.5
  dotted_border: ^2.1.0
  random_string:

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0



flutter:


  uses-material-design: true


  assets:
    - assets/images/





  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
