// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLmhIoBdSjhc4g3WWjylW2REvi-y-8hf4',
    appId: '1:130522425607:web:1c97ce8628425294793da2',
    messagingSenderId: '130522425607',
    projectId: 'sepehr-to-do-list-app',
    authDomain: 'sepehr-to-do-list-app.firebaseapp.com',
    storageBucket: 'sepehr-to-do-list-app.firebasestorage.app',
    measurementId: 'G-0P2XQ4F1B3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM5bzqxzb_Ku4xjQPFIs8c9yRA1kgdmto',
    appId: '1:130522425607:android:3f161d682be72eac793da2',
    messagingSenderId: '130522425607',
    projectId: 'sepehr-to-do-list-app',
    storageBucket: 'sepehr-to-do-list-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsC7p8lfqXJGtwtkdi52km8Qc4f7CIl7k',
    appId: '1:130522425607:ios:44254589beca4e29793da2',
    messagingSenderId: '130522425607',
    projectId: 'sepehr-to-do-list-app',
    storageBucket: 'sepehr-to-do-list-app.firebasestorage.app',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsC7p8lfqXJGtwtkdi52km8Qc4f7CIl7k',
    appId: '1:130522425607:ios:44254589beca4e29793da2',
    messagingSenderId: '130522425607',
    projectId: 'sepehr-to-do-list-app',
    storageBucket: 'sepehr-to-do-list-app.firebasestorage.app',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLmhIoBdSjhc4g3WWjylW2REvi-y-8hf4',
    appId: '1:130522425607:web:d525676585e6f5c6793da2',
    messagingSenderId: '130522425607',
    projectId: 'sepehr-to-do-list-app',
    authDomain: 'sepehr-to-do-list-app.firebaseapp.com',
    storageBucket: 'sepehr-to-do-list-app.firebasestorage.app',
    measurementId: 'G-YPJLVCHQNP',
  );

}